# Generated by Django 4.2.7 on 2023-12-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_pointsample_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='samples',
        ),
        migrations.DeleteModel(
            name='PointSample',
        ),
    ]
