# Generated by Django 4.2.7 on 2023-12-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_remove_samplecharacteristic_value'),
        ('points', '0004_pointsample_point_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSampleCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.characteristic')),
                ('point_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsample')),
            ],
        ),
    ]
