# Generated by Django 4.2.7 on 2023-12-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_point_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='samples',
        ),
    ]
