# Generated by Django 4.2.7 on 2023-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_remove_samplecharacteristic_value'),
        ('points', '0008_remove_point_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='samples',
            field=models.ManyToManyField(through='points.PointSample', to='samples.sample'),
        ),
    ]
