# Generated by Django 4.2.7 on 2023-12-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_point_samples'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointSampleCharacteristic',
        ),
    ]
