# Generated by Django 4.2.7 on 2023-12-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_characteristic_name_alter_sample_name_and_more'),
        ('points', '0010_delete_pointsamplecharacteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.characteristic')),
                ('pointSample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsample')),
            ],
        ),
    ]
