# Generated by Django 4.2.7 on 2023-12-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('expression', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
                ('сharacteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.characteristic')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='characteristics',
            field=models.ManyToManyField(through='samples.SampleCharacteristic', to='samples.characteristic'),
        ),
    ]
