# Generated by Django 4.2.7 on 2023-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_samplecharacteristic_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecharacteristic',
            name='value',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
