# Generated by Django 4.2.7 on 2023-12-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_samplecharacteristic_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecharacteristic',
            name='value',
        ),
    ]
