# Generated by Django 4.2.7 on 2023-12-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_remove_samplecharacteristic_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='samplecharacteristic',
            unique_together={('сharacteristic', 'sample')},
        ),
    ]
