# Generated by Django 4.2.7 on 2023-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
