# Generated by Django 4.2.7 on 2023-12-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0003_trip_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='editors',
            field=models.ManyToManyField(related_name='edited_trips', through='trips.TripEditor', to=settings.AUTH_USER_MODEL),
        ),
    ]
